class MtnOfferTableModel {
  final String num;
  final String name;
  final String price;
  final String numLink;
  final String codeUnified;
  final String catigory;
  final String cod;
  final String message;
  final String lnternet;
  const MtnOfferTableModel({
    required this.cod,
    required this.message,
    required this.lnternet,
    required this.num,
    required this.name,
    required this.price,
    required this.numLink,
    required this.codeUnified,
    required this.catigory,
  });
}

const List<MtnOfferTableModel> listMtnOfferTableModel = [
   MtnOfferTableModel(
      num: '15',
      name: 'ميجابايت دفع مسبق' '188',
      price: '1185',
      numLink: '15',
      codeUnified: 'PRESN188MB',
      catigory: 'باقات سمارت نت ',
      cod: '',
      message: '',
      lnternet: 'ميجا' '188'),
  MtnOfferTableModel(
      num: '16',
      name: 'ميجابايت دفع مسبق' '375',
      price: '1778',
      numLink: '16',
      codeUnified: 'PRESN375MB',
      catigory: 'باقات سمارت نت ',
      cod: '',
      message: '',
      lnternet: 'ميجا' '375'),
  MtnOfferTableModel(
      num: '17',
      name: 'ميجابايت دفع مسبق' '750',
      price: '2938',
      numLink: '17',
      codeUnified: 'PRESN750MB',
      catigory: 'باقات سمارت نت ',
      cod: '',
      message: '',
      lnternet: 'ميجا' '750'),
  MtnOfferTableModel(
      num: '13',
      name: 'مكس (300 دقيقة 400 رسالة 100 ميجا) دفع مسيق',
      price: '1185',
      numLink: '13',
      codeUnified: 'PREMIX300',
      catigory: 'باقات مكس ',
      cod: 'دقيقه' '300',
      message: 'رساله ' '400',
      lnternet: 'ميجا' '100'),
  MtnOfferTableModel(
      num: '14',
      name: 'مكس (600 دقيقة 700 رسالة 300 ميجا) دفع مسيق',
      price: '2370',
      numLink: '14',
      codeUnified: 'PREMlX600',
      catigory: 'باقات مكس ',
      cod: 'دقيقه' '600',
      message: 'رساله ' '700',
      lnternet: 'ميجا' '300'),
  MtnOfferTableModel(
      num: '15',
      name: 'ميجابايت دفع مسبق' '188',
      price: '1185',
      numLink: '15',
      codeUnified: 'PRESN188MB',
      catigory: 'باقات سمارت نت ',
      cod: '',
      message: '',
      lnternet: 'ميجا' '188'),
  MtnOfferTableModel(
      num: '16',
      name: 'ميجابايت دفع مسبق' '375',
      price: '1778',
      numLink: '16',
      codeUnified: 'PRESN375MB',
      catigory: 'باقات سمارت نت ',
      cod: '',
      message: '',
      lnternet: 'ميجا' '375'),
  MtnOfferTableModel(
      num: '17',
      name: 'ميجابايت دفع مسبق' '750',
      price: '2938',
      numLink: '17',
      codeUnified: 'PRESN750MB',
      catigory: 'باقات سمارت نت ',
      cod: '',
      message: '',
      lnternet: 'ميجا' '750'),
  MtnOfferTableModel(
      num: '18',
      name: 'جيجا دفع مسبق' '1',
      price: '4740',
      numLink: '18',
      codeUnified: 'PRESN15GB',
      catigory: 'باقات سمارت نت ',
      cod: '',
      message: '',
      lnternet: 'ميجا' '500'),
  // MtnOfferTableModel(
  //   num: '38',
  //   name: 'باقات مكس',
  //   price: '0',
  //   numLink: '0',
  //   codeUnified: '',
  // ),
  // MtnOfferTableModel(
  //   num: '39',
  //   name: 'سمارت نت دفع مسبق',
  //   price: '0',
  //   numLink: '0',
  //   codeUnified: '',
  // ),
  // MtnOfferTableModel(
  //   num: '40',
  //   name: 'باقة واصل دفع مسبق',
  //   price: '0',
  //   numLink: '0',
  //   codeUnified: '',
  // ),
  // MtnOfferTableModel(
  //   num: '41',
  //   name: 'باقات التواصل الأجتماعية دفع مسبق',
  //   price: '0',
  //   numLink: '0',
  //   codeUnified: '',
  // ),
  // MtnOfferTableModel(
  //   num: '43',
  //   name: 'بقة المكالمات دفع مسبق',
  //   price: '0',
  //   numLink: '0',
  //   codeUnified: '',
  // ),
  // MtnOfferTableModel(
  //   num: '44',
  //   name: 'باقات الرسائل دفع مسبق',
  //   price: '0',
  //   numLink: '0',
  //   codeUnified: '',
  // ),
  // MtnOfferTableModel(
  //   num: '45',
  //   name: 'باقة مكس الذهبية فوترة',
  //   price: '0',
  //   numLink: '0',
  //   codeUnified: '',
  // ),
  // MtnOfferTableModel(
  //   num: '46',
  //   name: 'باقة سمارت نت فوترة',
  //   price: '0',
  //   numLink: '0',
  //   codeUnified: '',
  // ),
  // MtnOfferTableModel(
  //   num: '47',
  //   name: 'باقات التواصل الأجتماعى فوترة',
  //   price: '0',
  //   numLink: '0',
  //   codeUnified: '',
  // ),
  MtnOfferTableModel(
      num: '48',
      name: 'باقة مكس بلس 200 دقيقه 200 رساله 200 ميجا دفع مسبق',
      price: '1485',
      numLink: '48',
      codeUnified: 'PREMIXPLUS',
      catigory: 'باقات مكس ',
      cod: 'دقيقه' '200',
      message: 'رساله ' '200',
      lnternet: 'ميجا' '200'),
  MtnOfferTableModel(
      num: '49',
      name:
          'باقة سوبر مكس 900 دقيقه داخل الشبكة + 100 دقيقة لجمع الشبكات + 1000 ميجا نت + 900 رسالة داخل الشبكة + 100 رسالة لجميع الشبكات دفع مسبق',
      price: '4977',
      numLink: '49',
      codeUnified: 'PRESUPERUIX',
      catigory: 'باقات مكس ',
      cod: 'دقيقه' '900',
      message: 'رساله ' '900',
      lnternet: 'ميجا' '1000'),
  // MtnOfferTableModel(
  //   num: '50',
  //   name: 'باقات مكس الجديده',
  //   price: '0',
  //   numLink: '0',
  //   codeUnified: '',
  // ),
  MtnOfferTableModel(
      num: '51',
      name: 'دقيقة دفع مسبق' '400',
      price: '1185',
      numLink: '51',
      codeUnified: 'PAE400Min',
      catigory: 'باقات المكالمات والرسائل',
      cod: 'دقيقه' '200',
      message: '',
      lnternet: ''),
  MtnOfferTableModel(
      num: '52',
      name: 'دقيقة فوترة' '400',
      price: '1185',
      numLink: '52',
      codeUnified: 'PCS400Min',
      catigory: 'باقات المكالمات والرسائل',
      cod: 'دقيقه' '400',
      message: '',
      lnternet: ''),
  MtnOfferTableModel(
      num: '53',
      name:
          'باقة سوبر مكس 900 دقيقه داخل الشبكة + 100 دقيقة لجمع الشبكات + 1000 ميجا نت + 900 رسالة داخل الشبكة + 100 رسالة لجميع الشبكات فوترة',
      price: '4977',
      numLink: '53',
      codeUnified: 'POSSUPERMIX',
      catigory: 'باقات مكس ',
      cod: 'دقيقه' '900',
      message: 'رساله ' '900',
      lnternet: 'ميجا' '1000'),
  MtnOfferTableModel(
      num: '54',
      name: 'باقة مكس بلس 200 دقيقه 200 رساله 200 ميجا فوتره',
      price: '1482',
      numLink: '54',
      codeUnified: 'POSMIXPLUS',
      catigory: 'باقات مكس ',
      cod: 'دقيقه' '200',
      message: 'رساله ' '200',
      lnternet: 'ميجا' '200'),
  MtnOfferTableModel(
      num: '55',
      name: 'جي اس ام الأسبوعية 200 دقيقة 200 رسالة 200 ميجا',
      price: '984',
      numLink: '0',
      codeUnified: 'PRE_GSM_Weekly',
      catigory: 'باقات مكس ',
      cod: 'دقيقه' '200',
      message: 'رساله ' '200',
      lnternet: 'ميجا' '200'),
  MtnOfferTableModel(
      num: '55',
      name: 'جي اس ام الشهرية 300 دقيقة 300 رسالة 300 ميجا',
      price: '1178',
      numLink: '0',
      codeUnified: 'PRE_GSM_Monthly',
      catigory: 'باقات مكس ',
      cod: 'دقيقه' '300',
      message: 'رساله ' '300',
      lnternet: 'ميجا' '300'),
];
